CREATE LINKED TABLE INFO(
    'org.h2.Driver',
    'jdbc:h2:tcp://localhost:8989/mem:simple-vision-core',
    'sa',
    '',
    'INFO'
);

INSERT INTO PRESCRIPTION (
    ID, PATIENT_ID, LEFT_SPHERE, LEFT_CYLINDER, LEFT_AXIS,
    RIGHT_SPHERE, RIGHT_CYLINDER, RIGHT_AXIS, PD
) SELECT PRESCRIPTION_ID, ID, LEFT_SPHERE, LEFT_CYLINDER,
        LEFT_AXIS, RIGHT_SPHERE, RIGHT_CYLINDER,
        RIGHT_AXIS, PD
  FROM INFO;