CREATE TABLE INFO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(45),
    ADDRESS VARCHAR(45),
    LEFT_SPHERE VARCHAR(45),
    LEFT_CYLINDER VARCHAR(45),
    LEFT_AXIS VARCHAR(45),
    RIGHT_SPHERE VARCHAR(45),
    RIGHT_CYLINDER VARCHAR(45),
    RIGHT_AXIS VARCHAR(45),
    PD VARCHAR(45),
    LENS_MATERIAL VARCHAR(45),
    LENS_ADDITIONS VARCHAR(45),
    LENS_STYLE VARCHAR(45),
    EMAIL VARCHAR(45),
    PHONE_NUMBER VARCHAR(45)
);