CREATE TABLE PRESCRIPTION (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  PATIENT_ID INT,
  LEFT_SPHERE VARCHAR(45),
  LEFT_CYLINDER VARCHAR(45),
  LEFT_AXIS VARCHAR(45),
  RIGHT_SPHERE VARCHAR(45),
  RIGHT_CYLINDER VARCHAR(45),
  RIGHT_AXIS VARCHAR(45),
  PD VARCHAR(45)
);