ALTER TABLE INFO DROP COLUMN LEFT_SPHERE;
ALTER TABLE INFO DROP COLUMN LEFT_CYLINDER;
ALTER TABLE INFO DROP COLUMN LEFT_AXIS;
ALTER TABLE INFO DROP COLUMN RIGHT_SPHERE;
ALTER TABLE INFO DROP COLUMN RIGHT_CYLINDER;
ALTER TABLE INFO DROP COLUMN RIGHT_AXIS;
ALTER TABLE INFO DROP COLUMN PD;